### ISSUE TITLE
Feature ~ to hide DefaultSyblos section

### ISSUE THREAD

**Issue by ghost** [pratikjshah/symbol-browser#1]
Hi! Thank you for this wonderful plugin, it solves the problem with the generation of guidelines for developers ;)

It would be great if you implemented this feature, as it would give you the opportunity to fully control the appearance of the page with elements and make cool video presentations ;)

![Снимок экрана 2019-06-20 в 5 33 28 ПП](https://user-images.githubusercontent.com/32170181/59857388-81d82080-9381-11e9-9f81-81c518bcc93b.png)

It would also be nice if you could take a caption to each section that appears above its caption

![Снимок экрана 2019-06-20 в 5 35 26 ПП](https://user-images.githubusercontent.com/32170181/59857526-c9f74300-9381-11e9-9880-9f5c4b9ab1a7.png)

**Comment by ghost** [comment]
And it would be great to be able to exclude individual symbols.

**Comment by pratikjshah** [comment]
Great suggestion on ability to hide certain symbols! I will work on it.

And the feature of hiding Default symbol is coming soon.

**Comment by ghost** [comment]
Great news, thank you.
