### ISSUE TITLE
A dialog to enter these meta descriptions to components and symbol browser window to be floating

### ISSUE THREAD

**Issue by designcraveyard** [pratikjshah/symbol-browser#10]

**Comment by pratikjshah** [comment]
Hi @designcraveyard, 
Thank you for reaching out.

Coming soon

- The Floating (always open) window is coming soon.
- Tabs for the active library (Quick navigation across libraries)

Will pick up next
- Form-based Meta description generation.

**Comment by pratikjshah** [comment]
Hi @designcraveyard. I have added this feature with the `v3.5.2` release. Please check it out here:  http://symbol-browser.pratikshah.website/
