### ISSUE TITLE
Issue ~ can't control the symbols

### ISSUE THREAD

**Issue by ghost** [pratikjshah/symbol-browser#2]
I can't control the symbols by changing the names. Version Of Sketch - 55.2

![Снимок экрана 2019-06-20 в 6 08 49 ПП](https://user-images.githubusercontent.com/32170181/59859954-66bbdf80-9386-11e9-8c2b-b86f23b7c577.png)

**Comment by pratikjshah** [comment]
Hi Attvud, Can you please describe what you mean by "can't control by changing name?"

Here is a step by step process of creating stickers https://github.com/pratikjshah/symbol-browser/wiki/Getting-started-with-Symbols-Browser#steps-to-get-started

**Comment by ghost** [comment]
Hi!

When I add the @ tag to the folders, everything works. But when I add it to the symbols, it doesn't work. They are not displayed in the corresponding section.

**Comment by pratikjshah** [comment]
Hi Artem,

You can take a look at this example Sketch Library:
https://sketch.cloud/s/DVnWq
To tag symbols or any layer, you have to

   1. Define Category and Sub-category:
   https://github.com/pratikjshah/symbol-browser/wiki/Getting-started-with-Symbols-Browser#32-define-categories
   2. If you tag defined category and use "@Category.SubCategory" as a
   suffix to a symbol, it will be added as a Symbol-object and not an
   instance. Which is similar to tagging an Artboard. Check guide here:
   https://github.com/pratikjshah/symbol-browser/wiki/Getting-started-with-Symbols-Browser#32-define-categories


Hope this helps.

--
Pratik Shah
(+ 91 8905750744)
PratikShah.Website <http://pratikshah.website>

**Comment by ghost** [comment]
This does not work for symbols. At least for me, I checked. For folders and artboards works, for symbols - no.

**Comment by pratikjshah** [comment]
I think I found the issue! I will fix it and release an update soon.
Thank you for pointing out.

--
Pratik Shah
(+ 91 8905750744)
PratikShah.Website <http://pratikshah.website>

**Comment by ghost** [comment]
Thank you for your prompt feedback ;)

**Comment by uxpreview** [comment]
I'm having the same issue. Additionally, the update to 2.1.1 is disabled.

**Comment by pratikjshah** [comment]
Hi, @ryankmccarty Thank you for reaching out. 

The reason currently you are not able re-group symbols is that it was more about system-driven, I am taking this as an enhancement.

**Comment by uxpreview** [comment]
@pratikjshah to be more clear, I am unable to apply stickers to symbols. Your test file is also missing this instance.

**Comment by pratikjshah** [comment]
Hey, @ryankmccarty you can tag any layer except SymbolArtboard as Stickers. In the test file, you can see Card - Symbol instances being marked as Stickers which will preserve your overrides.

**Comment by pratikjshah** [comment]
Hi, @ryankmccarty Now you can tag your Master Symbols directly to group them as per your needs. Please check it out here: http://symbol-browser.pratikshah.website/#features
