### ISSUE TITLE
Feature ~ ability to run symbol library indexing only manually

### ISSUE THREAD

**Issue by ghost** [pratikjshah/symbol-browser#3]
The fact is that many designers have a habit of constantly saving their work in the process (Ctrl+S).

In this regard, we constantly have to wait for a new character indexing. And it is extremely inconvenient.

It would be healthy to add the ability to index characters only by clicking in the plugin menu, ignoring the frequency of saving the document.

**Comment by pratikjshah** [comment]
Good point!
I will take this as an enhancement.
