### ISSUE TITLE
Poor performance with large libraries

### ISSUE THREAD

**Issue by Kondenko** [pratikjshah/symbol-browser#5]
I use Material Design symbols library and when I search for symbols Symbol Browser becomes very unresponsive. It might be a good idea to add debounce for text input events so search doesn't occur too often leading to freezes.

For a reference (heavy freezes in the beginning):

![Screen Recording 2019-07-31 at 18 57 22 2019-07-31 19_00_47](https://user-images.githubusercontent.com/6809803/62227977-89013e00-b3c5-11e9-9535-89dd34f40355.gif)

**Comment by pratikjshah** [comment]
Hi @Kondenko thank you for reaching out! I am working on optimization for search and will soon roll out the update!

**Comment by pratikjshah** [comment]
Hi @Kondenko with `v3.5.2` release the performance has been improved by **3x**
Please check it out here: http://symbol-browser.pratikshah.website/#features
