### ISSUE TITLE
Possible to provide a non-modal view?

### ISSUE THREAD

**Issue by rvr** [pratikjshah/symbol-browser#6]
It would be a nice enhancement to provide a non-modal option that would be a faster workflow for some users.

**Comment by pratikjshah** [comment]
hi @rvr This feature is coming soon! Stay Tuned! 🤘

**Comment by rvr** [comment]
Awesome, can't wait to see the new features. We're excited to try it with our design system.

**Comment by rvr** [comment]
Any news on this?

**Comment by pratikjshah** [comment]
Hi @rvr, Thank you for reminding me. Let me try to fix this soon.

**Comment by pratikjshah** [comment]
Hi, @rvr I have added this feature with the `v3.5.2` release. Please check it out here: http://symbol-browser.pratikshah.website/
