### ISSUE TITLE
Each time I want to "View Design System" it is indexing all the symbols 

### ISSUE THREAD

**Issue by Runarda** [pratikjshah/symbol-browser#9]
Hi i downloaded the plugin today. Each time I want to "View Design System" it is indexing all the symbols. I am running Sketch version Version 63.1. 
I guess the problem have something to do with the design system being very large?

**Comment by pratikjshah** [comment]
Hi @Runarda 
Plugin indexes the library only when the "Sketch Library" has been updated from last time. Having said that.. possible reasons for frequent file changes can be...

1. You have the Sketch Library open and as Sketch has an auto-save feature, Plugin thinks that the file has been updated.
2. You are working on the Sketch Library itself!

Thank you for reaching out. Let me know if you are still facing the issue.
